/* ============================================================================
   LegalDesk — Corresponding Sections data
   ----------------------------------------------------------------------------
   SIX statutes in three reform pairs:
       IPC  <-> BNS   (penal)      IEA <-> BSA (evidence)     CrPC <-> BNSS (procedure)

   Row format (enter each mapping ONCE per pair; the tool handles both directions):
     { old:"302", oldH:"Punishment for murder", new:"103", newH:"Punishment for murder" }
     - numbers are STRINGS; keep sub-parts ("304A"), or a bare section ("103").
     - no counterpart? use new:"" / old:"" and put a note in newH/oldH ("Omitted").

   SOURCE NOTE: compiled from the widely-published BNS/BNSS/BSA concordance
   (daily-use provisions). VERIFY sub-section numbers against the official
   Gazette concordance before relying on them in court. Extend freely.
   ========================================================================== */

window.CORRESP = {
  ipc_bns: {
    oldName: "IPC, 1860",  oldShort: "IPC",
    newName: "BNS, 2023",  newShort: "BNS",
    rows: [
      { old:"34",   oldH:"Acts done by several persons in furtherance of common intention", new:"3(5)", newH:"Common intention" },
      { old:"96",   oldH:"Things done in private defence",              new:"34",  newH:"Things done in private defence" },
      { old:"120A", oldH:"Definition of criminal conspiracy",           new:"61(1)", newH:"Criminal conspiracy (definition)" },
      { old:"120B", oldH:"Punishment of criminal conspiracy",           new:"61(2)", newH:"Punishment of criminal conspiracy" },
      { old:"124A", oldH:"Sedition",                                    new:"152", newH:"Act endangering sovereignty, unity and integrity of India (replaces sedition)" },
      { old:"141",  oldH:"Unlawful assembly",                           new:"189(1)", newH:"Unlawful assembly" },
      { old:"143",  oldH:"Punishment \u2014 member of unlawful assembly", new:"189(2)", newH:"Punishment \u2014 member of unlawful assembly" },
      { old:"147",  oldH:"Punishment for rioting",                      new:"191(2)", newH:"Punishment for rioting" },
      { old:"148",  oldH:"Rioting, armed with deadly weapon",           new:"191(3)", newH:"Rioting armed with deadly weapon" },
      { old:"149",  oldH:"Unlawful assembly \u2014 constructive liability", new:"190", newH:"Every member of unlawful assembly guilty of offence in prosecution of common object" },
      { old:"153A", oldH:"Promoting enmity between groups",             new:"196", newH:"Promoting enmity between different groups" },
      { old:"171",  oldH:"Wearing garb/token used by public servant",   new:"170", newH:"Wearing garb or carrying token used by public servant with fraudulent intent" },
      { old:"186",  oldH:"Obstructing public servant in discharge of functions", new:"221", newH:"Obstructing public servant in discharge of public functions" },
      { old:"188",  oldH:"Disobedience to order duly promulgated by public servant", new:"223", newH:"Disobedience to order duly promulgated by public servant" },
      { old:"191",  oldH:"Giving false evidence",                       new:"227", newH:"Giving false evidence" },
      { old:"201",  oldH:"Causing disappearance of evidence",           new:"238", newH:"Causing disappearance of evidence of offence" },
      { old:"212",  oldH:"Harbouring offender",                         new:"249", newH:"Harbouring offender" },
      { old:"228A", oldH:"Disclosure of identity of victim of certain offences", new:"72", newH:"Disclosure of identity of victim of certain offences" },
      { old:"268",  oldH:"Public nuisance",                             new:"270", newH:"Public nuisance" },
      { old:"279",  oldH:"Rash driving on public way",                  new:"281", newH:"Rash driving or riding on a public way" },
      { old:"292",  oldH:"Sale of obscene books, etc.",                 new:"294", newH:"Sale of obscene books, etc." },
      { old:"294",  oldH:"Obscene acts and songs",                      new:"296", newH:"Obscene acts and songs" },
      { old:"299",  oldH:"Culpable homicide (definition)",              new:"100", newH:"Culpable homicide (definition)" },
      { old:"300",  oldH:"Murder (definition)",                         new:"101", newH:"Murder (definition)" },
      { old:"302",  oldH:"Punishment for murder",                       new:"103", newH:"Punishment for murder" },
      { old:"304",  oldH:"Punishment for culpable homicide not amounting to murder", new:"105", newH:"Punishment for culpable homicide not amounting to murder" },
      { old:"304A", oldH:"Causing death by negligence",                 new:"106(1)", newH:"Causing death by negligence" },
      { old:"304B", oldH:"Dowry death",                                 new:"80",  newH:"Dowry death" },
      { old:"306",  oldH:"Abetment of suicide",                         new:"108", newH:"Abetment of suicide" },
      { old:"307",  oldH:"Attempt to murder",                           new:"109", newH:"Attempt to murder" },
      { old:"308",  oldH:"Attempt to commit culpable homicide",         new:"110", newH:"Attempt to commit culpable homicide" },
      { old:"309",  oldH:"Attempt to commit suicide",                   new:"",    newH:"No direct counterpart (not re-enacted; cf. BNS 226 \u2014 attempt to suicide to compel/restrain public servant)" },
      { old:"319",  oldH:"Hurt (definition)",                           new:"113(1)", newH:"Hurt (definition)" },
      { old:"320",  oldH:"Grievous hurt (definition)",                  new:"116", newH:"Grievous hurt (definition)" },
      { old:"323",  oldH:"Punishment for voluntarily causing hurt",     new:"115(2)", newH:"Voluntarily causing hurt" },
      { old:"324",  oldH:"Voluntarily causing hurt by dangerous weapons", new:"118(1)", newH:"Voluntarily causing hurt by dangerous weapons or means" },
      { old:"325",  oldH:"Punishment for voluntarily causing grievous hurt", new:"117(2)", newH:"Voluntarily causing grievous hurt" },
      { old:"326",  oldH:"Voluntarily causing grievous hurt by dangerous weapons", new:"118(2)", newH:"Voluntarily causing grievous hurt by dangerous weapons or means" },
      { old:"326A", oldH:"Voluntarily causing grievous hurt by acid",   new:"124(1)", newH:"Voluntarily causing grievous hurt by use of acid, etc." },
      { old:"326B", oldH:"Voluntarily throwing/attempting to throw acid", new:"124(2)", newH:"Voluntarily throwing or attempting to throw acid" },
      { old:"332",  oldH:"Voluntarily causing hurt to deter public servant", new:"121(1)", newH:"Voluntarily causing hurt to deter public servant from his duty" },
      { old:"336",  oldH:"Act endangering life or personal safety of others", new:"125", newH:"Act endangering life or personal safety of others" },
      { old:"337",  oldH:"Causing hurt by act endangering life",        new:"125(a)", newH:"Causing hurt by act endangering life or personal safety" },
      { old:"338",  oldH:"Causing grievous hurt by act endangering life", new:"125(b)", newH:"Causing grievous hurt by act endangering life or personal safety" },
      { old:"339",  oldH:"Wrongful restraint (definition)",             new:"126(1)", newH:"Wrongful restraint (definition)" },
      { old:"340",  oldH:"Wrongful confinement (definition)",           new:"127(1)", newH:"Wrongful confinement (definition)" },
      { old:"341",  oldH:"Punishment for wrongful restraint",           new:"126(2)", newH:"Punishment for wrongful restraint" },
      { old:"342",  oldH:"Punishment for wrongful confinement",         new:"127(2)", newH:"Punishment for wrongful confinement" },
      { old:"351",  oldH:"Assault (definition)",                        new:"130", newH:"Assault (definition)" },
      { old:"354",  oldH:"Assault or criminal force to woman with intent to outrage modesty", new:"74", newH:"Assault or criminal force to woman with intent to outrage her modesty" },
      { old:"354A", oldH:"Sexual harassment",                          new:"75",  newH:"Sexual harassment" },
      { old:"354B", oldH:"Assault/criminal force to woman with intent to disrobe", new:"76", newH:"Assault or use of criminal force to woman with intent to disrobe" },
      { old:"354C", oldH:"Voyeurism",                                   new:"77",  newH:"Voyeurism" },
      { old:"354D", oldH:"Stalking",                                    new:"78",  newH:"Stalking" },
      { old:"359",  oldH:"Kidnapping",                                  new:"137(1)", newH:"Kidnapping" },
      { old:"363",  oldH:"Punishment for kidnapping",                   new:"137(2)", newH:"Punishment for kidnapping" },
      { old:"375",  oldH:"Rape (definition)",                           new:"63",  newH:"Rape (definition)" },
      { old:"376",  oldH:"Punishment for rape",                         new:"64",  newH:"Punishment for rape" },
      { old:"376D", oldH:"Gang rape",                                   new:"70",  newH:"Gang rape" },
      { old:"377",  oldH:"Unnatural offences",                          new:"",    newH:"No direct counterpart in BNS (not re-enacted)" },
      { old:"378",  oldH:"Theft (definition)",                          new:"303(1)", newH:"Theft (definition)" },
      { old:"379",  oldH:"Punishment for theft",                        new:"303(2)", newH:"Punishment for theft" },
      { old:"380",  oldH:"Theft in dwelling house",                     new:"305", newH:"Theft in dwelling house, means of transport, etc." },
      { old:"384",  oldH:"Punishment for extortion",                    new:"308(2)", newH:"Extortion" },
      { old:"390",  oldH:"Robbery (definition)",                        new:"309(1)", newH:"Robbery (definition)" },
      { old:"392",  oldH:"Punishment for robbery",                      new:"309(4)", newH:"Punishment for robbery" },
      { old:"395",  oldH:"Punishment for dacoity",                      new:"310(2)", newH:"Dacoity" },
      { old:"405",  oldH:"Criminal breach of trust (definition)",       new:"316(1)", newH:"Criminal breach of trust (definition)" },
      { old:"406",  oldH:"Punishment for criminal breach of trust",     new:"316(2)", newH:"Punishment for criminal breach of trust" },
      { old:"411",  oldH:"Dishonestly receiving stolen property",       new:"317(2)", newH:"Dishonestly receiving stolen property" },
      { old:"415",  oldH:"Cheating (definition)",                       new:"318(1)", newH:"Cheating (definition)" },
      { old:"417",  oldH:"Punishment for cheating",                     new:"318(2)", newH:"Punishment for cheating" },
      { old:"420",  oldH:"Cheating and dishonestly inducing delivery of property", new:"318(4)", newH:"Cheating and dishonestly inducing delivery of property" },
      { old:"425",  oldH:"Mischief (definition)",                       new:"324(1)", newH:"Mischief (definition)" },
      { old:"441",  oldH:"Criminal trespass (definition)",              new:"329(1)", newH:"Criminal trespass (definition)" },
      { old:"447",  oldH:"Punishment for criminal trespass",            new:"329(3)", newH:"Punishment for criminal trespass" },
      { old:"448",  oldH:"Punishment for house-trespass",               new:"329(4)", newH:"Punishment for house-trespass" },
      { old:"463",  oldH:"Forgery (definition)",                        new:"336(1)", newH:"Forgery (definition)" },
      { old:"465",  oldH:"Punishment for forgery",                      new:"336(2)", newH:"Punishment for forgery" },
      { old:"468",  oldH:"Forgery for purpose of cheating",             new:"336(3)", newH:"Forgery for purpose of cheating" },
      { old:"471",  oldH:"Using as genuine a forged document",          new:"340(2)", newH:"Using as genuine a forged document or electronic record" },
      { old:"489A", oldH:"Counterfeiting currency notes or bank-notes", new:"178", newH:"Counterfeiting currency notes or bank notes" },
      { old:"499",  oldH:"Defamation (definition)",                     new:"356(1)", newH:"Defamation (definition)" },
      { old:"500",  oldH:"Punishment for defamation",                   new:"356(2)", newH:"Punishment for defamation" },
      { old:"503",  oldH:"Criminal intimidation (definition)",          new:"351(1)", newH:"Criminal intimidation (definition)" },
      { old:"504",  oldH:"Intentional insult to provoke breach of peace", new:"352", newH:"Intentional insult with intent to provoke breach of the peace" },
      { old:"506",  oldH:"Punishment for criminal intimidation",        new:"351(2)", newH:"Punishment for criminal intimidation" },
      { old:"509",  oldH:"Word/gesture intended to insult modesty of a woman", new:"79", newH:"Word, gesture or act intended to insult modesty of a woman" },
      { old:"511",  oldH:"Attempting to commit offences",               new:"62",  newH:"Punishment for attempting to commit offences" }
    ]
  },
  iea_bsa: {
    oldName: "Indian Evidence Act, 1872", oldShort: "IEA",
    newName: "BSA, 2023",                 newShort: "BSA",
    rows: [
      { old:"3",   oldH:"Interpretation clause (definitions)",          new:"2",   newH:"Definitions" },
      { old:"5",   oldH:"Evidence may be given of facts in issue and relevant facts", new:"5", newH:"Evidence may be given of facts in issue and relevant facts" },
      { old:"6",   oldH:"Relevancy of facts forming part of same transaction (res gestae)", new:"4", newH:"Relevancy of facts forming part of same transaction" },
      { old:"8",   oldH:"Motive, preparation and previous/subsequent conduct", new:"6", newH:"Motive, preparation and previous or subsequent conduct" },
      { old:"11",  oldH:"When facts not otherwise relevant become relevant", new:"9", newH:"When facts not otherwise relevant become relevant" },
      { old:"17",  oldH:"Admission (definition)",                       new:"15",  newH:"Admission (definition)" },
      { old:"24",  oldH:"Confession caused by inducement, threat or promise irrelevant", new:"22", newH:"Confession caused by inducement, threat, coercion or promise" },
      { old:"25",  oldH:"Confession to police officer not to be proved", new:"23(1)", newH:"Confession to police officer not to be proved" },
      { old:"26",  oldH:"Confession while in police custody",           new:"23(2)", newH:"Confession by accused while in custody of police" },
      { old:"27",  oldH:"How much of information received from accused may be proved", new:"23(2) proviso", newH:"How much of information received from accused may be proved" },
      { old:"32",  oldH:"Statements by persons who cannot be called (dying declaration)", new:"26", newH:"Cases in which statement of relevant fact by person who is dead, etc., is relevant" },
      { old:"45",  oldH:"Opinions of experts",                          new:"39",  newH:"Opinions of experts" },
      { old:"60",  oldH:"Oral evidence must be direct",                 new:"55",  newH:"Oral evidence must be direct" },
      { old:"61",  oldH:"Proof of contents of documents",              new:"56",  newH:"Proof of contents of documents" },
      { old:"63",  oldH:"Secondary evidence",                          new:"58",  newH:"Secondary evidence" },
      { old:"65",  oldH:"Cases in which secondary evidence relating to documents may be given", new:"60", newH:"Cases in which secondary evidence relating to documents may be given" },
      { old:"65B", oldH:"Admissibility of electronic records",          new:"63",  newH:"Admissibility of electronic records" },
      { old:"101", oldH:"Burden of proof",                              new:"104", newH:"Burden of proof" },
      { old:"103", oldH:"Burden of proof as to particular fact",        new:"106", newH:"Burden of proof as to particular fact" },
      { old:"106", oldH:"Burden of proving fact especially within knowledge", new:"109", newH:"Burden of proving fact especially within knowledge" },
      { old:"114", oldH:"Court may presume existence of certain facts", new:"119", newH:"Court may presume existence of certain facts" },
      { old:"118", oldH:"Who may testify",                              new:"124", newH:"Who may testify" },
      { old:"133", oldH:"Accomplice",                                   new:"138", newH:"Accomplice" },
      { old:"137", oldH:"Examination-in-chief, cross-examination, re-examination", new:"143", newH:"Examination-in-chief, cross-examination and re-examination" },
      { old:"145", oldH:"Cross-examination as to previous statements in writing", new:"148", newH:"Cross-examination as to previous statements in writing" }
    ]
  },
  crpc_bnss: {
    oldName: "CrPC, 1973", oldShort: "CrPC",
    newName: "BNSS, 2023", newShort: "BNSS",
    rows: [
      { old:"41",  oldH:"When police may arrest without warrant",       new:"35",  newH:"When police may arrest without warrant" },
      { old:"41A", oldH:"Notice of appearance before police officer",   new:"35(3)", newH:"Notice of appearance before police officer" },
      { old:"46",  oldH:"Arrest how made",                              new:"43",  newH:"Arrest how made" },
      { old:"50",  oldH:"Person arrested to be informed of grounds",    new:"47",  newH:"Person arrested to be informed of grounds of arrest" },
      { old:"54",  oldH:"Examination of arrested person by medical officer", new:"53", newH:"Examination of arrested person by medical officer" },
      { old:"91",  oldH:"Summons to produce document or other thing",   new:"94",  newH:"Summons to produce document or other thing" },
      { old:"125", oldH:"Order for maintenance of wives, children and parents", new:"144", newH:"Order for maintenance of wives, children and parents" },
      { old:"144", oldH:"Power to issue order in urgent cases of nuisance/apprehended danger", new:"163", newH:"Power to issue order in urgent cases of nuisance or apprehended danger" },
      { old:"154", oldH:"Information in cognizable cases (FIR)",         new:"173", newH:"Information in cognizable cases" },
      { old:"156", oldH:"Police officer's power to investigate cognizable case", new:"175", newH:"Police officer's power to investigate cognizable case" },
      { old:"161", oldH:"Examination of witnesses by police",           new:"180", newH:"Examination of witnesses by police" },
      { old:"162", oldH:"Statements to police not to be signed",        new:"181", newH:"Statements to police not to be signed; use of statements in evidence" },
      { old:"164", oldH:"Recording of confessions and statements",      new:"183", newH:"Recording of confessions and statements" },
      { old:"167", oldH:"Procedure when investigation cannot be completed in 24 hours", new:"187", newH:"Procedure when investigation cannot be completed in twenty-four hours" },
      { old:"173", oldH:"Report of police officer on completion of investigation", new:"193", newH:"Report of police officer on completion of investigation" },
      { old:"190", oldH:"Cognizance of offences by Magistrates",        new:"210", newH:"Cognizance of offences by Magistrates" },
      { old:"197", oldH:"Prosecution of Judges and public servants (sanction)", new:"218", newH:"Prosecution of Judges and public servants" },
      { old:"200", oldH:"Examination of complainant",                   new:"223", newH:"Examination of complainant" },
      { old:"202", oldH:"Postponement of issue of process",             new:"225", newH:"Postponement of issue of process" },
      { old:"204", oldH:"Issue of process",                             new:"227", newH:"Issue of process" },
      { old:"207", oldH:"Supply of copy of police report and documents to accused", new:"230", newH:"Supply to accused of copy of police report and other documents" },
      { old:"227", oldH:"Discharge",                                    new:"250", newH:"Discharge" },
      { old:"228", oldH:"Framing of charge",                            new:"251", newH:"Framing of charge" },
      { old:"239", oldH:"When accused shall be discharged (warrant/police report)", new:"262", newH:"When accused shall be discharged" },
      { old:"294", oldH:"No formal proof of certain documents",         new:"330", newH:"No formal proof of certain documents" },
      { old:"311", oldH:"Power to summon material witness / examine person present", new:"348", newH:"Power to summon material witness, or examine person present" },
      { old:"313", oldH:"Power to examine the accused",                 new:"351", newH:"Power to examine the accused" },
      { old:"320", oldH:"Compounding of offences",                      new:"359", newH:"Compounding of offences" },
      { old:"357", oldH:"Order to pay compensation",                    new:"395", newH:"Order to pay compensation" },
      { old:"374", oldH:"Appeals from convictions",                     new:"415", newH:"Appeals from convictions" },
      { old:"378", oldH:"Appeal in case of acquittal",                  new:"419", newH:"Appeal in case of acquittal" },
      { old:"397", oldH:"Calling for records to exercise powers of revision", new:"438", newH:"Calling for records to exercise powers of revision" },
      { old:"401", oldH:"High Court's powers of revision",              new:"442", newH:"High Court's powers of revision" },
      { old:"436", oldH:"In what cases bail to be taken (bailable offence)", new:"478", newH:"In what cases bail to be taken" },
      { old:"437", oldH:"When bail may be taken in case of non-bailable offence", new:"480", newH:"When bail may be taken in case of non-bailable offence" },
      { old:"438", oldH:"Direction for grant of bail to person apprehending arrest (anticipatory bail)", new:"482", newH:"Direction for grant of bail to person apprehending arrest" },
      { old:"439", oldH:"Special powers of High Court/Sessions Court regarding bail", new:"483", newH:"Special powers of High Court or Court of Session regarding bail" },
      { old:"482", oldH:"Saving of inherent powers of High Court",      new:"528", newH:"Saving of inherent powers of High Court" }
    ]
  }
};
